- name: Example for downloading Alteon configuration file
  hosts: localhost
  vars_files:
    - vars/alteon_params.yml

  tasks:
    - name: Alteon device configuration
      radware.radware_alteon.alteon_device_configuration:
        provider: "{{ radware_provider }}"
        command: config_download
        passphrase: radware
        include_keys: true
        file_path: /tmp/alteon-config
