on:
  schedule:
    - cron: '30 5 * * 3'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Automation-Hub API key
        run: |
            curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token \
            -d grant_type=refresh_token -d client_id="cloud-services" \
            -d refresh_token="${{ secrets.AUTOMATION_HUB_KEY }}" \
            --fail --silent --show-error --output /dev/null
